### ISSUE TITLE
Validation données

### ISSUE THREAD

**Issue by OrnellaT** [werobot-france/eurobot2020-scoresimulator#6]
Merci beaucoup pour ce simulateur de scores ! 
Ce serait top si vous pouviez rajouter une validation des données, par exemple, il est actuellement possible de rentrer ces données : 
Bouées dans le port : 100 / Bouées dans le chenal coloré : 200 / Paires de bouées : 300
Alors qu'il n'y a que 50 bouées disponibles en tout sur le terrain, dont seulement 37 accessibles pour chaque équipe, que les bouées présentes dans un chenal le sont automatiquement dans le port (donc le nombre de bouées dans le chenal ne peut pas être plus grand que le nombre de bouées dans le port) et qu'il ne peut pas y avoir plus de la moitié de paires de bouées que du nombre de bouées de la bonne couleur. 

Par ailleurs, je ne peux pas décocher la case "non forfait" même si je n'ai rentré aucun point avant. Ceci dit, on peut supposer que l'on n'a pas besoin d'un simulateur pour savoir que si l'on est forfait on a zéro points. Mais dans ce cas peut-être que simplement indiquer "5 pts" sans case à cocher (actuellement grisée) serait plus judicieux. 

Bon courage pour la suite !

**Comment by Ornella83** [comment]
Je m'étais fait ce tableau sous google sheet : https://docs.google.com/spreadsheets/d/1EqVYOS5BUjkShNAomUWGXdA8o7JCwqJPd4gkdrb5p8M/edit?usp=sharing
L'interface est bien moins sympa que la vôtre mais j'ai essayé de vérifier la cohérence des données (vous pouvez voir les formules dans la colonne "Erreur").

**Comment by lefuturiste** [comment]
Merci pour ces issues, je vais y travailler

**Comment by lefuturiste** [comment]
J'ai mit à jour le site, il faut vider le cache Ctrl+Shift+R pour avoir la nouvelle version. Qu'en pensez vous ? (J'ai pas forcement tout implémenté, mais au moins ça devrait être à jour par rapport au nouveau règlement)

**Comment by OrnellaT** [comment]
> J'ai mit à jour le site, il faut vider le cache Ctrl+Shift+R pour avoir la nouvelle version. Qu'en pensez vous ? (J'ai pas forcement tout implémenté, mais au moins ça devrait être à jour par rapport au nouveau règlement)

Ca me semble très bien comme ça (messages d'erreur en rouge sous les cases invalides). 
Si je comprends bien il n'y a que la case non forfait qui n'a pas été mise à jour ? Mais c'est très bien comme ça :)

Merci beaucoup !
