### ISSUE TITLE
Règlement modifié

### ISSUE THREAD

**Issue by OrnellaT** [werobot-france/eurobot2020-scoresimulator#7]
Le comptage des points pour le retour à la zone de départ a été modifié pour la version 2021 du règlement : 
Le comptage des points est différencié en fonction du nombre de robots présentés sur le terrain au lancement
du match.
Équipe avec un seul robot :
• 20 points si le robot est valide dans la zone de mouillage indiquée par la girouette;
• 6 points si le robot est valide dans l’autre zone de mouillage;
Équipe avec deux robots :
• 10 points par robot valide dans la zone de mouillage indiquée par la girouette;
• 3 points par robot valide dans l’autre zone de mouillage;

**Comment by lefuturiste** [comment]
Mis à jour en même temps que l'issue #6

**Comment by OrnellaT** [comment]
Bonjour, 
Pour le coup là il y a une erreur car le cas où l'équipe a deux robots et que l'un des deux n'est pas du tout dans le port n'est pas pris en compte. En effet il semblerait que le nombre de robots total soit considéré dans le simulateur comme égal au nombre de robots qui sont soit dans la zone indiquée par la girouette soit dans l'autre zone. 
Donc là dans le simulateur si je mets :
Robots valides dans la zone indiqué par la girouette : 0
Robots valides dans l'autre zone : 1
---> 6 points 
Alors que ce serait 3 points si j'avais deux robots dont un qui est resté ailleurs sur le terrain. 
Robots valides dans la zone indiqué par la girouette : 1
Robots valides dans l'autre zone : 0
---> 20 points
Alors que ce serait 10 si j'avais deux robots dont un qui est resté ailleurs sur le terrain. 

Dans les autres cas ça fonctionne très bien. 

Je ne vois pas d'autre solution pour traiter ce cas que de rajouter un champ pour indiquer le nombre de robots de l'équipe.

**Comment by lefuturiste** [comment]
Effectivement c'est une erreur de logique impardonnable x)
Je voulais me simplifier la vie au max résultat je dois faire un changement.  :joy: 
Du coup j'ai rajouté un champ pour le nombre de robots de l'équipe et j'ai update le site.

**Comment by OrnellaT** [comment]
Super ! 
Bon, je pinaille un tout petit peu : 
Il n'y a pas de test pour vérifier qu'on ne met pas plus de robots dans le port qu'on en a indiqué au total, donc il est possible de faire : 
Nombre de robots au total : 1
Robots valides dans la zone indiqué par la girouette : 2
Robots valides dans l'autre zone : 0
Ce qui calcule 40 points (j'imagine 20 * nb robot dans la zone indiquée, ici 2 bien qu'impossible). 

Mais il suffit de ne pas écrire de bêtises dans ce champ et ça fonctionne parfaitement comme ça ! :) 

(Et au passage, il manque un "e" à "zone indiquéE" )

Merci encore pour ce joli simulateur :)

**Comment by lefuturiste** [comment]
Effectivement c'est mieux comme ça, j'ai mit à jour le site
Merci pour ces remarques et bug reports.
